### PR TITLE
Fix lineWidth object bug with fillColor: null

### LINKED ISSUE #1001: `lineWidth` object doesn't work correctly with `plain` theme or `fillColor: null`
When defining `lineWidth` as an object with a single side border, if `theme` is `plain` or `fillColor` is `null`, cells will get full borders all around not respecting `lineWidth` object.

image

code :

```js
doc.autoTable({
  head: [['Name', 'Email', 'Country']],
  body: [
    ['David', 'david@example.com', 'Sweden'],
    ['Castille', 'castille@example.com', 'Spain'],
  ],
  theme: 'plain',
  styles: {
    // fillColor: null,
    lineColor: 0,
    lineWidth: {top: 0, bottom: 0.3, right: 0, left: 0},
  },
})
```

jsDPF: `v2.5.1`
jsPDF-AutoTable: `v3.6.0`

### PR DESCRIPTION
**Pull request by mmghv**
Fixes #1001

Refs : #730, #961, #978

`fillColor: null` caused cells to have full borders even when `lineWidth` is an object with partial borders.

This is caused by calling `rect()` to draw the background with `null` as `fillStyle` when `fillColor` is null :

https://github.com/simonbengtsson/jsPDF-AutoTable/blob/4c04f6a089b9dea919e84fee5fff649552cd49b8/src/tableDrawer.ts#L409-L410

## Reproduce code

```js
doc.autoTable({
  head: [['Name', 'Email', 'Country']],
  body: [
    ['David', 'david@example.com', 'Sweden'],
    ['Castille', 'castille@example.com', 'Spain'],
  ],
  theme: 'plain',
  styles: {
    // fillColor: null,
    lineColor: 0,
    lineWidth: {top: 0, bottom: 0.3, right: 0, left: 0},
  },
})
```

## Before

image

## After

image

### CODE REVIEW

File: src/documentHandler.ts [hunk 1]
```diff
@@ -111,14 +111,12 @@ export class DocHandler {
...
-  rect(x: number, y: number, width: number, height: number, fillStyle: 'S' | 'F' | 'DF' | 'FD' | null) {
-    if (!['S', 'F', 'DF', 'FD', null].some((v) => v === fillStyle)) {
-      throw new TypeError(
-        `Invalid value '${fillStyle}' passed to rect. Allowed values are: 'S', 'F', 'DF', 'FD', null`
-      )
-    }
+  rect(x: number, y: number, width: number, height: number, fillStyle: 'S' | 'F' | 'DF' | 'FD') {
+    // null is excluded from fillStyle possible values because it isn't needed
+    // and is prone to bugs as it's used to postpone setting the style
+    // https://rawgit.com/MrRio/jsPDF/master/docs/jsPDF.html#rect
```
Comment (mmghv) [inline src/documentHandler.ts:119]: I've excluded `null` from being used as `fillStyle` with `rect()` which is intended to postpone setting the style when drawing multiple shapes at once, this was first introduced in [this PR](https://github.com/simonbengtsson/jsPDF-AutoTable/pull/961/files#diff-9b88a8b078366d3e6e564db8c0305c8a0fe9671199b6c9d055ab06c42d83f075R108). this shouldn't be used as it could lead to bugs like this when misused.

Comment (mmghv) [inline src/documentHandler.ts:119]: I've excluded `null` from being used as `fillStyle` with `rect()` which is intended to postpone setting the style when drawing multiple shapes at once, this was first introduced in [this PR](https://github.com/simonbengtsson/jsPDF-AutoTable/pull/961/files#diff-9b88a8b078366d3e6e564db8c0305c8a0fe9671199b6c9d055ab06c42d83f075R108). this shouldn't be used as it could lead to bugs like this when misused.

**Comment by simonbengtsson** [comment]
Awesome! Tagging in @MikeDabrowski here as well in case he wants to review as well.

**Comment by MikeDabrowski** [comment]
Yep, brilliant! Thx for the fix and tagging.
I tested it on my project and had no regressions
